# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main
- master

resources:
- repo: self

variables:
  - group: hackatonxp
  - name: tag
    value: '$(Build.BuildId)'

stages:
- stage: sBuild
  displayName: Build and push stage
  jobs:  
  - job: jBuild
    displayName: Build and push stage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'hackatonxp'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: sDeploy
  displayName: Deploy to Conteiner Instance
  jobs:
    - deployment: jDeploy
      environment: 'Hackaton XP'
      displayName: Deploy to Conteiner Instance
      workspace:
        clean: all
      strategy:
        runOnce:
          deploy:
            pool:
              vmImage: 'ubuntu-latest'
            steps:
              - task: AzureCLI@2
                displayName: Deploy to Conteiner Instance
                inputs:
                  azureSubscription: 'dam.net.br'
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    try {
                      $list = $(az container list --resource-group hackaton-xp | ConvertFrom-JSON)
                      $hackatonxp = $list.conteiners | Where-Object { $_.name -eq "hackatonxp" }
                      if($null -ne $hackatonxp) {
                        az container delete --name hackatonxp --resource-group hackaton-xp --yes
                      }
                    } catch {
                      Write-Host "##[info]Cointeiner not found."
                    }

                    az container create --name hackatonxp --resource-group hackaton-xp --image hackatonxp.azurecr.io/hackatonxp:$(tag) --cpu 1 --memory 1 --registry-login-server "hackatonxp.azurecr.io" --registry-username "hackatonxp" --registry-password $(RegistryPassword) --dns-name-label hackatonxp --ports 4001